[package]
name = "rokid_max_gyro"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
cgmath = "0.18"
hidapi = "2.6"
bytemuck = "1.16"
vqf-rs = { version = "0.2", features = ["f32", "motion-bias-estimation"] }
byteorder = "1.4"
